version: '3'
services:
  rstudio:
    image: rocker/rstudio:latest
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=abcd
    container_name: rstudio_container
    volumes:
      - ./:/home/rstudio
